### ISSUE TITLE
WSL2 Errors when running script

### ISSUE THREAD

**Issue by GhostlyCrowd** [RedPill-TTG/redpill-load#1]
First error is the "Cache" folder doesn't exist from git and if you don't make it the script fails to make it and download the PAT. 

Second issue I have I'm not sure what the issue is but it Fails to repack the ramdisk with no actual failure output. 

`jeff@JJ_VIRI:~/redpill-load$ ./build-loader.sh 'DS3615xs' '6.2.4-25556'
[#] Checking runtime for required tools... [OK]
[#] PAT file /home/jeffj/redpill-load/cache/ds3615xs_25556.pat not found - downloading from https://global.download.synology.com/download/DSM/release/6.2.4/25556/DSM_DS3615xs_25556.pat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  271M  100  271M    0     0  62.9M      0  0:00:04  0:00:04 --:--:-- 63.7M
[#] Verifying /home/jeffj/redpill-load/cache/ds3615xs_25556.pat file... [OK]
[#] Unpacking /home/jeffj/redpill-load/cache/ds3615xs_25556.pat file to /home/jeffj/redpill-load/build/1627490645/pat-ds3615xs_25556-unpacked... [OK]
[#] Verifying /home/jeffj/redpill-load/build/1627490645/pat-ds3615xs_25556-unpacked/zImage file... [OK]
[#] Patching /home/jeffj/redpill-load/build/1627490645/pat-ds3615xs_25556-unpacked/zImage to /home/jeffj/redpill-load/build/1627490645/zImage-patched... [OK]
[#] Verifying /home/jeffj/redpill-load/build/1627490645/pat-ds3615xs_25556-unpacked/rd.gz file... [OK]
[#] Unpacking /home/jeffj/redpill-load/build/1627490645/pat-ds3615xs_25556-unpacked/rd.gz file to /home/jeffj/redpill-load/build/1627490645/rd-ds3615xs_25556-unpacked... [OK]
[#] Apply patches to /home/jeffj/redpill-load/build/1627490645/rd-ds3615xs_25556-unpacked... [OK]
[#] Patching config files in ramdisk... [OK]
[#] Adding OS config patching... [OK]
[#] Repacking ramdisk to /home/jeffj/redpill-load/build/1627490645/rd-patched-ds3615xs_25556.gz... [ERR]
[!] Failed to repack compressed ramdisk

*** Process will exit ***`

Any ideas?

**Comment by ilovepancakes95** [comment]
I am experiencing the same issue, but running Ubuntu directly.

**Comment by GhostlyCrowd** [comment]
> I am experiencing the same issue, but running Ubuntu directly.
> 
> EDIT: Running the build script as sudo fixed the issue for me.

I found the same thing too I thought I had clicked "submit" for an edit but I apparently didn't.

**Comment by ttg-public** [comment]
Thank you for these reports guys!

The cache folder issue is fixed (https://github.com/RedPill-TTG/redpill-load/commit/74cd6b0860f00a66e56d9d8a51732043851565b9). As for the permission issue the mount operation has to be run from a user with disk operations permission. This is distro-dependent - usually adding the user to `disk` group or running as `root` solves the issue.

If it's still a problem please reopen this issue.
