### ISSUE TITLE
error building DS3615xs 7.0-41222: mount: special device /dev/loop0p2 does not exist

### ISSUE THREAD

**Issue by goldengit** [RedPill-TTG/redpill-load#10]
Hi!

got the following error when creating loader image:  mount: special device /dev/loop0p1 does not exist

running on debian 8

see full output log below:

user1@debian8-synobuild:~/syno-build/redpill-load$ sudo ./build-loader.sh DS3615xs 7.0-41222
[#] Checking runtime for required tools... [OK]
[#] Verifying /home/user1/syno-build/redpill-load/cache/ds3615xs_41222.pat file... [OK]
[#] Unpacking /home/user1/syno-build/redpill-load/cache/ds3615xs_41222.pat file to /home/user1/syno-build/redpill-load/build/1629062770/pat-ds3615xs_41222-unpacked... [OK]
[#] Verifying /home/user1/syno-build/redpill-load/build/1629062770/pat-ds3615xs_41222-unpacked/zImage file... [OK]
[#] Patching /home/user1/syno-build/redpill-load/build/1629062770/pat-ds3615xs_41222-unpacked/zImage to /home/user1/syno-build/redpill-load/build/1629062770/zImage-patched... [OK]
[#] Verifying /home/user1/syno-build/redpill-load/build/1629062770/pat-ds3615xs_41222-unpacked/rd.gz file... [OK]
[#] Unpacking /home/user1/syno-build/redpill-load/build/1629062770/pat-ds3615xs_41222-unpacked/rd.gz file to /home/user1/syno-build/redpill-load/build/1629062770/rd-ds3615xs_41222-unpacked... [OK]
[#] Apply patches to /home/user1/syno-build/redpill-load/build/1629062770/rd-ds3615xs_41222-unpacked... [OK]
[#] Patching config files in ramdisk... [OK]
[#] Adding OS config patching... [OK]
[#] Repacking ramdisk to /home/user1/syno-build/redpill-load/build/1629062770/rd-patched-ds3615xs_41222.gz... [OK]
[#] Generating GRUB config... [OK]
[#] Creating loader image at /home/user1/syno-build/redpill-load/images/redpill-DS3615xs_7.0-41222_b1629062770.img... mount: special device /dev/loop0p1 does not exist

[!] Failed to mount /dev/loop0p1 (partition 1 of /home/user1/syno-build/redpill-load/images/redpill-DS3615xs_7.0-41222_b1629062770.img) to /home/user1/syno-build/redpill-load/build/1629062770/img-mnt/part-1

*** Process will exit ***
mount: special device /dev/loop0p2 does not exist

[!] Failed to mount /dev/loop0p2 (partition 2 of /home/user1/syno-build/redpill-load/images/redpill-DS3615xs_7.0-41222_b1629062770.img) to /home/user1/syno-build/redpill-load/build/1629062770/img-mnt/part-2

*** Process will exit ***
[OK]
[#] Cleaning up... 
[!] Failed to unmount 

umount: undefined mountpoint

*** Process will exit ***

**Comment by goldengit** [comment]
correection

**Comment by ttg-public** [comment]
That is... new. `losetup` succeeded but failed. Can you try typing `losetup` in console and posting the result? If there's anything there try doing `losetup -d /dev/loop?` to detach all loops and try running the build again.

**Comment by goldengit** [comment]
Hi!

doing sudo losetup -d /dev/loop0 worked! it seems that loop device was mounted but after performing the suggested step the build process worked without hitch :) thank you - keep up the great work you guys are wonderful!
