### ISSUE TITLE
Enable to start DSM bromolow 6.2.4 on ESXi 7.0

### ISSUE THREAD

**Issue by OrpheeGT** [RedPill-TTG/redpill-load#12]
Hello,

Not able to pass disk initialisation on boot, hangs at 56/57%

[load.txt](https://github.com/RedPill-TTG/redpill-load/files/7013964/load.txt)

Using sata-dom

loader img mounted on SATA 0:0
virtual disk 32GB mounted on SATA 0:1

Tried to add a new SATA controller like done with Jun's loader, and set disk to SATA 1:0 but disk not detected in DSM. same with SCSI.

**Comment by OrpheeGT** [comment]
Can be closed, actually it was user error :

https://xpenology.com/forum/topic/45795-redpill-the-new-loader-for-624-discussion/?do=findComment&comment=211814

**Comment by dmc31a42** [comment]
I also have this problem and fixed with "VMDK pre-allocated~"
