### ISSUE TITLE
[!] Failed to repack flat ramdisk

### ISSUE THREAD

**Issue by mzcls** [RedPill-TTG/redpill-load#15]
[#] Checking runtime for required tools... [OK]
[#] Verifying /home/mz/Public/ubuntu/mz/DSM/redpill-load/cache/ds918+_25556.pat file... [OK]
[#] Unpacking /home/mz/Public/ubuntu/mz/DSM/redpill-load/cache/ds918+_25556.pat file to /home/mz/Public/ubuntu/mz/DSM/redpill-load/build/1629596516/pat-ds918+_25556-unpacked... [OK]
[#] Verifying /home/mz/Public/ubuntu/mz/DSM/redpill-load/build/1629596516/pat-ds918+_25556-unpacked/zImage file... [OK]
[#] Patching /home/mz/Public/ubuntu/mz/DSM/redpill-load/build/1629596516/pat-ds918+_25556-unpacked/zImage to /home/mz/Public/ubuntu/mz/DSM/redpill-load/build/1629596516/zImage-patched... [OK]
[#] Verifying /home/mz/Public/ubuntu/mz/DSM/redpill-load/build/1629596516/pat-ds918+_25556-unpacked/rd.gz file... [OK]
[#] Unpacking /home/mz/Public/ubuntu/mz/DSM/redpill-load/build/1629596516/pat-ds918+_25556-unpacked/rd.gz file to /home/mz/Public/ubuntu/mz/DSM/redpill-load/build/1629596516/rd-ds918+_25556-unpacked... [OK]
[#] Apply patches to /home/mz/Public/ubuntu/mz/DSM/redpill-load/build/1629596516/rd-ds918+_25556-unpacked... [OK]
[#] Patching config files in ramdisk... [OK]
[#] Adding OS config patching... [OK]
[#] Repacking ramdisk to /home/mz/Public/ubuntu/mz/DSM/redpill-load/build/1629596516/rd-patched-ds918+_25556.gz... 
[!] Failed to repack flat ramdisk

*** Process will exit ***

This error occurred when I made the mirror. Is there anything I did wrong?

**Comment by ttg-public** [comment]
Yes, it's a permission problem. Can we assume you've solved the issue?

**Comment by cqranjian** [comment]
> Yes, it's a permission problem. Can we assume you've solved the issue?

Compiled with root account is not the problem.

**Comment by cqranjian** [comment]
> Yes, it's a permission problem. Can we assume you've solved the issue?

How to extend card driver?My network adapter does not support.

**Comment by ttg-public** [comment]
Currently we don't have a sane way of handling custom drivers. It's tracked in other issues as well ;)
