### ISSUE TITLE
Can you add support for 918+ in EXSI 6.7?

### ISSUE THREAD

**Issue by cqranjian** [RedPill-TTG/redpill-load#20]
now ,it can loaded.But Failed to install up to 55%。

Trying 192.168.2.189...
Connected to 192.168.2.189.
Escape character is '^]'.

DiskStation login:
DiskStation login: root

Synology strongly advises you not to run commands as the root user, who has
the highest privileges on the system. Doing so may cause major damages
to the system. Please note that if you choose to proceed, all consequences are
at your own risk.

BusyBox v1.30.1 () built-in shell (ash)

DiskStation> ls
DiskStation> fdisk -l
Disk /dev/sdm: 128 MB, 134217728 bytes, 262144 sectors
16 cylinders, 255 heads, 63 sectors/track
Units: sectors of 1 * 512 = 512 bytes

Device  Boot StartCHS    EndCHS        StartLBA     EndLBA    Sectors  Size Id Type
/dev/sdm1    0,32,33     6,62,56           2048     100351      98304 48.0M 83 Linux
/dev/sdm2    6,62,57     15,205,62       100352     253951     153600 75.0M 83 Linux
/dev/sdm3    15,205,63   16,81,1         253952     262143       8192 4096K 83 Linux
Disk /dev/sdn: 16 GB, 17179869184 bytes, 33554432 sectors
2088 cylinders, 255 heads, 63 sectors/track
Units: sectors of 1 * 512 = 512 bytes

Device  Boot StartCHS    EndCHS        StartLBA     EndLBA    Sectors  Size Id Type
/dev/sdn1    0,32,33     310,37,47         2048    4982527    4980480 2431M fd Linux raid autodetect
/dev/sdn2    310,37,48   571,58,63      4982528    9176831    4194304 2048M fd Linux raid autodetect
Disk /dev/md0: 2431 MB, 2549940224 bytes, 4980352 sectors
622544 cylinders, 2 heads, 4 sectors/track
Units: sectors of 1 * 512 = 512 bytes

Disk /dev/md0 doesn't contain a valid partition table
Disk /dev/md1: 2047 MB, 2147418112 bytes, 4194176 sectors
524272 cylinders, 2 heads, 4 sectors/track
Units: sectors of 1 * 512 = 512 bytes

Disk /dev/md1 doesn't contain a valid partition table
DiskStation>

**Comment by ttg-public** [comment]
This is a problem with boot device. See https://github.com/RedPill-TTG/redpill-lkm/issues/14#issuecomment-917816935 

If this doesn't solve the problem feel free to reopen this issue.
