### ISSUE TITLE
The load can not work on my HW: msi b560m MB + i5-10400

### ISSUE THREAD

**Issue by xinsui01** [RedPill-TTG/redpill-load#26]
Hi,
   First of all, thank you very much for the contributions of the project team members.
   I'm a newer to synology. 
   
   My hardware configuration is as follows:
   - MB: MSI MAG B560M Mortar WiFi (with RTL8125b)
   - CPU: i5-10400
   
   The 7.01 bootloader of 918+ I have downloaded from https://www.openos.org/threads/ds918-ds3615xs7-01.3529/. I have changed vid/pid/sn/mac, and it's not work for my physical equipment with UEFI mode. The output info stopped at  'Starting kernel' as follow:
  
![81631431042_ pic](https://user-images.githubusercontent.com/20895125/132977502-b3963596-457e-4b2d-90cf-e29aad7554f2.jpg)

 I can neither find the device with synology assistant nor find the IP on my router. Is there any suggestions to me to mark it working.

**Comment by brucexo** [comment]
我也是……

**Comment by pocopico** [comment]
You need to recreate the image with latest intel drivers https://www.intel.com/content/www/us/en/support/articles/000005480/ethernet-products.html

**Comment by ghost** [comment]
Related issue: https://github.com/pocopico/rp-ext/issues/8

Add related driver and install successful, then reboot, the api show not_install and reinstall. 

loop ...

any suggestion?

**Comment by pocopico** [comment]
Maybe an extension fails to load.

Start with the minimum required extensions and start adding one by one.

**Comment by ghost** [comment]
Ok,  I will remove all inner drivers in redpill-load and only add intel driver. recreate the bootloader later.
Thx pocopico (˘͈ᵕ ˘͈❀)

**Comment by ghost** [comment]
[dmesg.log](https://github.com/RedPill-TTG/redpill-load/files/7514354/dmesg.log)

@pocopico I think it may not be the problem of the driver, can you help me see where the problem is from the log?

I only have one HHD，and fresh install.

(*￣︶￣) TYVM

**Comment by pocopico** [comment]
Which extensions are you using ? I will try to verify

**Comment by ghost** [comment]
r8125
