### ISSUE TITLE
ESXi Install Error 13 / Failed to Mount /dev/synoboot2

### ISSUE THREAD

**Issue by ilovepancakes95** [RedPill-TTG/redpill-load#6]
Building off the discussion started in the Xpenology forum....

I was unable to get a serial console login prompt originally when booting loader on ESXi despite VM and loader web interface working. Per a tip from user RedwinX on the telegram channel, changing ttyS2 to ttyS1 via Grub "e" menu allowed the login prompt to appear on VM Serial Port 2. However, serial port prints slowly via telnet (about 1 line per second) and inserts a "-" after every character I type. None the less, it works to access /var/log/messages per @ttg-public request on the forum for more info to resolve Error 13.

See the resulting full /var/log/messages below which was collected about a fresh attempt at installing DSM 6.2.4 via redpill-load. For reference, I tried 7.0 as well using a .ko produced with Synology's toolchain and jumkey's 7.0 branch for loader and and I get the same result. It seems the install stops and errors out when it tries to mount /dev/synoboot2. Not sure what to try from here.

https://pastebin.com/x8JCr6r2

**Comment by ilovepancakes95** [comment]
@ttg-public Forgot to also provide /var/log/junior_reason yesterday per your forum request. It only has 1 line, which exists before and after install attempt. See below.

`-Exit on error [12] No raid status in path /sys/block/md0/md/array_state, go to junior mode...`

**Comment by ttg-public** [comment]
> inserts a "-" after every character I type.

Yeah, we saw that too. It's annoying but we don't have a solution for that problem yet. It is related to the serial swapping which is finicky (as well, nobody in the right mind predicted switching serial ports which are defined in such a way for 50 years ;)).



> It seems the install stops and errors out when it tries to mount /dev/synoboot2.
If you look at the log there are 3 lines dealing with USB devices detection:
```
Aug  3 08:33:10 kernel: [   21.648972] <redpill/boot_device_shim.c:70> Found new device <vid=1d6b, pid=0002> - didn't match expected <vid=46f4, pid=0001>
Aug  3 08:33:10 kernel: [   21.674594] <redpill/boot_device_shim.c:70> Found new device <vid=1d6b, pid=0003> - didn't match expected <vid=46f4, pid=0001>
Aug  3 08:33:10 kernel: [   22.203400] <redpill/boot_device_shim.c:70> Found new device <vid=0e0f, pid=0003> - didn't match expected <vid=46f4, pid=0001>
```

None of them are a USB storage device. Currently RP supports booting from USB devices only. The SATA DOM support is not done yet. We are not sure if ESXi allows for adding virtual USB drives? If not we will prioritize this in the pipeline.

**Comment by ilovepancakes95** [comment]
> nobody in the right mind predicted switching serial ports which are defined in such a way for 50 years

lol, sounds like a Synology thing to do....

> None of them are a USB storage device. Currently RP supports booting from USB devices only. The SATA DOM support is not done yet. We are not sure if ESXi allows for adding virtual USB drives? If not we will prioritize this in the pipeline.

We were starting to think this in the telegram group, the couple people testing ESXi especially since Jun's loader has a boot entry for ESXi specifically, which does "loadlinux 918 sata" instead of "loadlinux 918 usb".

I have never seen an official way in ESXi/vCenter to add a virtual USB device, only a pass-through hardware USB stick. Which gave me an idea to write redpill-load img to an actual USB, pass it through to VM and try and boot off that but the VM doesn't see the USB as a boot option so guess we'll have to wait for your SATA DOM implementation in order to test more on ESXi :)

**Comment by ttg-public** [comment]
@ilovepancakes95 Did completion of https://github.com/RedPill-TTG/redpill-lkm/issues/12 solve your issue with ESXi?

**Comment by ilovepancakes95** [comment]
> @ilovepancakes95 Did completion of [RedPill-TTG/redpill-lkm#12](https://github.com/RedPill-TTG/redpill-lkm/issues/12) solve your issue with ESXi?

Yes it did! Only major issue I've come across with ESXi/DS3615xs is [RedPill-TTG/redpill-lkm#14](https://github.com/RedPill-TTG/redpill-lkm/issues/14). Otherwise, RedPill DSM 7 ESXi works pretty well, boots/loads very fast compared to Jun's loaders with DSM 6. Hasn't crashed after leaving running for more than 24 hours.
