### ISSUE TITLE
Powerbutton DS3615xs on Proxmox ?

### ISSUE THREAD

**Issue by Odroid13** [RedPill-TTG/redpill-load#63]
Thank you for your work.

The power button from Proxmox does not work DS3615xs.

Works perfectly with DS918+

(redpill-acpid).

Thanks

**Comment by jimmyGALLAND** [comment]
when you build your image
try   ./ext-manager.sh add  https://raw.githubusercontent.com/jimmyGALLAND/redpill-ext/master/acpid/rpext-index.json

**Comment by Odroid13** [comment]
> when you build your image
> try ./ext-manager.sh add https://raw.githubusercontent.com/jimmyGALLAND/redpill-ext/master/acpid/rpext-index.json

Works perfectly.

Thank you very much.

This is what I added: 

./redpill_tool_chain.sh add https://github.com/jimmyGALLAND/redpill-ext/raw/master/acpid/rpext-index.json
