### ISSUE TITLE
Failed to install DSM Failed to install the file the file is probably corrupt. VMware ESXi 7.0.2

### ISSUE THREAD

**Issue by AkideLiu** [RedPill-TTG/redpill-load#64]
Try to install DSM 7.0.1 on VMware ESXi, 7.0.2, 17867351 followed this instruction: https://github.com/pocopico/tinycore-redpill

Got the error:
Failed to install DSM Failed to install the file the file is probably corrupt.

The loader could be successful boot till install the synology .pat system.

below is the device info : 

<img width="478" alt="image" src="https://user-images.githubusercontent.com/41593290/158911932-0919f357-8732-4c39-a3e9-90c5466ffb08.png">

The log info retrieved from /var/log/message via telnet is attached below 

[redpill_loader_install_7.0.1_with_esxi_7.0.2.log](https://github.com/RedPill-TTG/redpill-load/files/8295309/redpill_loader_install_7.0.1_with_esxi_7.0.2.log)

**Comment by pocopico** [comment]
These are typical no synoboot issues 

Did you select Sata in grub ? 
Did you set the loader disk to a sata controller ?

**Comment by AkideLiu** [comment]
> These are typical no synoboot issues
> 
> Did you select Sata in grub ? 

Yes, i selected SATA in Grub.

>Did you set the loader disk to a sata controller ?

The loader disk is selected to [IDE 0 controller](https://github.com/pocopico/tinycore-redpill/issues/11#issuecomment-1019529046) because the loader can not boot if connect to a SATA bus, and data disk connected to SATA controller

for instance, the error of loader connect to SATA controller :

_Unsupported or invalid disk type 2 for 'sata0:2'. Ensure that the disk has been imported._

**Comment by BobWs** [comment]
Having the same problem! Did you find out a solution for this yet?

**Comment by AkideLiu** [comment]
> Having the same problem! Did you find out a solution for this yet?

Solution found, and there is an awesome step by step tutorial, I would suggest the problem occurred with the boot disk and data disk on the same SATA controller.

https://www.youtube.com/watch?v=3EI7nzlnbyk

**Comment by rosyidcho** [comment]
I have the same problem in my setup, got the solution here:

https://www.youtube.com/watch?v=UaVixedAVdQ

Hope it help....
