### ISSUE TITLE
Failed extract K=>V pairs from /redpill-load/config/DS3615xs/6.2.4-25556/config.json:.grub.menu_entries

### ISSUE THREAD

**Issue by goldengit** [RedPill-TTG/redpill-load#8]
Hi!
followed directions to place redpill.ko in appropriate directory and created user_config.json. When running ./build-loader.sh DS3615xs 6.2.4-25556 the script runs and downloads pat file and does its configurations however it fails with error keys_unsorted is not defined - see below:

[#] Checking runtime for required tools... [OK]
[#] Verifying /home/user1/syno-build/redpill-load/cache/ds3615xs_25556.pat file... [OK]
[#] Unpacking /home/user1/syno-build/redpill-load/cache/ds3615xs_25556.pat file to /home/user1/syno-build/redpill-load/build/1628813312/pat-ds3615xs_25556-unpacked... [OK]
[#] Verifying /home/user1/syno-build/redpill-load/build/1628813312/pat-ds3615xs_25556-unpacked/zImage file... [OK]
[#] Patching /home/user1/syno-build/redpill-load/build/1628813312/pat-ds3615xs_25556-unpacked/zImage to /home/user1/syno-build/redpill-load/build/1628813312/zImage-patched... [OK]
[#] Verifying /home/user1/syno-build/redpill-load/build/1628813312/pat-ds3615xs_25556-unpacked/rd.gz file... [OK]
[#] Unpacking /home/user1/syno-build/redpill-load/build/1628813312/pat-ds3615xs_25556-unpacked/rd.gz file to /home/user1/syno-build/redpill-load/build/1628813312/rd-ds3615xs_25556-unpacked... [OK]
[#] Apply patches to /home/user1/syno-build/redpill-load/build/1628813312/rd-ds3615xs_25556-unpacked... [OK]
[#] Patching config files in ramdisk... [OK]
[#] Adding OS config patching... [OK]
[#] Repacking ramdisk to /home/user1/syno-build/redpill-load/build/1628813312/rd-patched-ds3615xs_25556.gz... [OK]
[#] Generating GRUB config... 
[!] Failed extract K=>V pairs from /home/user1/syno-build/redpill-load/config/DS3615xs/6.2.4-25556/config.json:.grub.menu_entries

error: keys_unsorted is not defined
.grub.menu_entries|keys_unsorted|.[]                   1 compile error

*** Process will exit ***

let me know if there is anything else I can try !

Thanks in advance,

Ren

**Comment by dodo-dk** [comment]
Your JQ Version is probably to old.
Use this:
https://xpenology.com/forum/topic/45795-redpill-the-new-loader-for-624-discussion/?do=findComment&comment=209708

**Comment by goldengit** [comment]
That worked perfect! redpill .img built successfully!
