### ISSUE TITLE
Failed to install dsm7

### ISSUE THREAD

**Issue by Gigasnow** [RedPill-TTG/redpill-load#9]
I build the loader by myself and correctly edited the vid and pid, but I still failed to install dsm7 on my physical B365 platform. After uploading the install package, the webpage shows error code 13 and says that my install package is broken and need re-downloading.

**Comment by lily148** [comment]
@Gigasnow , may I know how to do you solve this?? I have the same problem like you..

**Comment by Gigasnow** [comment]
> @Gigasnow , may I know how to do you solve this?? I have the same problem like you..

I didn't fix it. Just wait for the stable version to release.
